/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author USUARIO
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        botaoCadastro = new javax.swing.JMenu();
        cadastroLivro = new javax.swing.JMenuItem();
        cadastroVendedor = new javax.swing.JMenuItem();
        cadastroCliente = new javax.swing.JMenuItem();
        botaoVendas = new javax.swing.JMenu();
        vendasLivro = new javax.swing.JMenuItem();
        vendasRelatorio = new javax.swing.JMenuItem();
        botaoSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuBar.setOpaque(false);

        botaoCadastro.setMnemonic('f');
        botaoCadastro.setText("Cadastro");

        cadastroLivro.setMnemonic('o');
        cadastroLivro.setText("Livro");
        botaoCadastro.add(cadastroLivro);

        cadastroVendedor.setMnemonic('s');
        cadastroVendedor.setText("Vendedor");
        cadastroVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroVendedorActionPerformed(evt);
            }
        });
        botaoCadastro.add(cadastroVendedor);

        cadastroCliente.setMnemonic('a');
        cadastroCliente.setText("Cliente");
        cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroClienteActionPerformed(evt);
            }
        });
        botaoCadastro.add(cadastroCliente);

        menuBar.add(botaoCadastro);

        botaoVendas.setMnemonic('e');
        botaoVendas.setText("Vendas");

        vendasLivro.setMnemonic('t');
        vendasLivro.setText("Livro");
        botaoVendas.add(vendasLivro);

        vendasRelatorio.setMnemonic('y');
        vendasRelatorio.setText("Gerar relatório");
        vendasRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendasRelatorioActionPerformed(evt);
            }
        });
        botaoVendas.add(vendasRelatorio);

        menuBar.add(botaoVendas);

        botaoSair.setMnemonic('h');
        botaoSair.setText("Sair");
        botaoSair.setToolTipText("");
        menuBar.add(botaoSair);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroVendedorActionPerformed

    private void cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroClienteActionPerformed

    private void vendasRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendasRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendasRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu botaoCadastro;
    private javax.swing.JMenu botaoSair;
    private javax.swing.JMenu botaoVendas;
    private javax.swing.JMenuItem cadastroCliente;
    private javax.swing.JMenuItem cadastroLivro;
    private javax.swing.JMenuItem cadastroVendedor;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem vendasLivro;
    private javax.swing.JMenuItem vendasRelatorio;
    // End of variables declaration//GEN-END:variables

}
